version: '3.8'

services:
  symfony_app:
    build:
      context: ./streemi/
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - ./streemi:/app:delegated
    environment:
      APP_ENV: dev
