version: '3.8'

services:
  app:
    build:
      context: ./streemi/
      dockerfile: Dockerfile
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
